security:
  encoders:
    App\Entity\User:
      algorithm: "argon2i"
      memory_cost: "%env(ARGON2I_MEMORY_COST)%"
      time_cost: "%env(ARGON2I_TIME_COST)%"
      threads: "%env(ARGON2I_THREADS)%"
  providers:
    main:
      entity: { class: "App\\Entity\\User", property: "username" }
  firewalls:
    main:
      pattern: ^/
      stateless: true
      anonymous: true

  access_control:
    - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/users, roles: IS_AUTHENTICATED_FULLY }
  role_hierarchy:
    ROLE_USER: ROLE_USER
    ROLE_ADMIN: [ROLE_ADMIN, ROLE_USER]
