security:
  encoders:
    App\Entity\User:
      algorithm: "sodium"
      memory_cost: 4096
      time_cost: 4
  providers:
    main:
      entity: { class: "App\\Entity\\User", property: "username" }
  firewalls:
    main:
      pattern: ^/
      anonymous: true
      guard:
        authenticators:
          - App\Security\LoginFormAuthenticator
      logout:
        path: security.logout

  access_control:
    - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/users, roles: IS_AUTHENTICATED_FULLY }
  role_hierarchy:
    ROLE_USER: ROLE_USER
    ROLE_ADMIN: [ROLE_ADMIN, ROLE_USER]
